# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: PyLadiesCon Portal Docs
site_url: https://pyladiescon-portal-docs.netlify.app
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  favicon: assets/favicon.ico
  palette:
    primary: "pink"
  features:
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.action.edit
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - About:
    - PyLadiesCon Portal: about/index.md
    - Team: about/team.md
  - Developer Guide:
    - Setup Guide: developer/setup.md
    - Contributing: developer/contributing.md
    - How Tos: developer/howto.md
    - Markdown Emails: developer/markdown-emails.md
    - Deployment: developer/deployment.md
  - User Guide:
    - Get started: user/get_started.md
    - Core Team: user/core_team.md
    - Volunteers: user/volunteer.md
    - Sponsors: user/sponsor.md
  - Policies:
    - Terms of Service: policies/terms_of_use.md
    - Acceptable Use Policy: policies/acceptable_use_policy.md
    - Code of Conduct: https://global-conference-2025.netlify.app/en/coc/
  - Portal: https://portal.pyladies.com/
repo_url: https://github.com/pyladies/pyladiescon-portal
repo_name: pyladies/pyladiescon-portal
edit_uri: edit/main/docs/
extra:
  homepage: https://conference.pyladies.com
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/2fUN4ddVfP
      name: Join our Discord
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@pyladies
      name: Follow us on Mastodon
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/pyladiescon.bsky.social
      name: Follow us on BlueSky
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/pyladiescon
      name: Connect with us on LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/pyladiescon
      name: Follow us on Instagram
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@pyladiesglobal
      name: Subscribe to our YouTube Channel
    - icon: material/hand-coin
      link: https://2025.conference.pyladies.com/en/donate/
      name: Donate to PyLadiesCon
    - icon: fontawesome/brands/github
      link: https://github.com/pyladies/pyladiescon-portal
      name: Contribute to our repository
plugins:
  - social
  - tags
  - rss
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: pyladies/pyladiescon-portal
      branch: main
